### ISSUE TITLE
Functionality with Node 6.x.x 

### ISSUE THREAD

**Issue by Sugarcaen** [frankhale/nw-edge-example#7]
I've been trying to get edgeJS running with Node 6.x.x. There's currently a pull request on @tjanczuk 's repo, but no action. Most likely you're going to have to update the readme. Again.

Using @medicomp 's fork I get a 'Module Version Mismatch' error

**Comment by frankhale** [comment]
I've created https://github.com/frankhale/nwjs-edge-example2 to deal with Edge.js being behind the curve on this respect. Additionally nwjs-edge-example2 also addresses the ridiculous complexity of getting native modules to work in NW.js by side stepping it and using regular Node and some IPC mechanism to talk instead of using it in directly in NW.js. That said, Edge doesn't support 6.x.x yet so I've used the latest version of Node Edge works with. Please see that example for details on this solution.

This example "nwjs-edge-example1" demonstrates building Edge directly for NW.js but it cannot be updated until Edge works with 6.x.x.

**Comment by frankhale** [comment]
It's likely that I may not update this example to work directly in NW.js because I've had great success keeping Node modules running inside a regular Node process and just communicate in some way to NW.js (eg. I prefer Socket.IO because it's simple). 

I'm considering https://github.com/frankhale/nwjs-edge-example2 and the way it goes about tackling this issue as the way I'm going to go in the future. Building native modules so they run directly in NW.js is really a horrible experience all around and the documentation on NW.js's site is spotty and a bit outdated. It's very difficult to get this way working but it's very simple to get it working in other ways like example2 demonstrates.

**Comment by Sugarcaen** [comment]
Thanks for the response, and the insight. Our experience has lined up with yours pretty directly. Sparse documentation, and variable version timelines have been killing me. I'll check out example 2, it seems more in line with our paradigms, and way easier to maintain.
